# user config settings
name: vulcan

resolution: "1536x1024"
hfw: 150.e-6
beam_type: "Electron"
autocontrast: True
save: False
gamma: # gamma correction parameters
  enabled: True
  min_gamma: 0.15
  max_gamma: 1.8
  scale_factor: 0.01
  threshold: 46 # px

dose_base: 100.e-9 # in s
n_passes: 1
vpd: 0.38 # in um^3 / nC, Xenon @ 30kV
imaging_current: 20.e-12 # in A
milling_current: 60.e-9 # in A
max_hfw: 800.e-6 # in m
pixel_size: 5.e-9 # in m
pattern_pixel_size: 100.e-9 # in m
position_x: 0.e-6 # in m
position_y: 0.e-6 # in m
invert: True
send: True
save_path: recreation_sub_um_100us
shuffle: True
clear: True

scale: True
scale_factor: 1.2136

# TODO: method from average DT or similar?